src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column(length: 200)]
    private ?string $adresse = null;

    #[ORM\Column(length: 100)]
    private ?string $ville = null;

    #[ORM\Column(length: 10)]
    private ?string $cp = null;

    #[ORM\Column(length: 15)]
    private ?string $numTel = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCommande = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $user = null;

    #[ORM\OneToMany(targetEntity: CommandeProduit::class, mappedBy: 'commande')]
    private Collection $CommandeProduits;

    public function __construct()
    {
        $this->CommandeProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->numTel;
    }

    public function setNumTel(string $numTel): static
    {
        $this->numTel = $numTel;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->dateCommande;
    }

    public function setDateCommande(\DateTimeInterface $dateCommande): static
    {
        $this->dateCommande = $dateCommande;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, CommandeProduit>
     */
    public function getCommandeProduits(): Collection
    {
        return $this->CommandeProduits;
    }

    public function addCommandeProduit(CommandeProduit $CommandeProduit): static
    {
        if (!$this->CommandeProduits->contains($CommandeProduit)) {
            $this->CommandeProduits->add($CommandeProduit);
            $CommandeProduit->setCommande($this);
        }

        return $this;
    }

    public function removeCommandeProduit(CommandeProduit $CommandeProduit): static
    {
        if ($this->CommandeProduits->removeElement($CommandeProduit)) {
            // set the owning side to null (unless already changed)
            if ($CommandeProduit->getCommande() === $this) {
                $CommandeProduit->setCommande(null);
            }
        }

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('nom',TextType::class)
        ->add('prenom',TextType::class)
        ->add('adresse',TextType::class)
        ->add('cp',TextType::class)
        ->add('ville',TextType::class)
        ->add('numTel',NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;


use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Produit;
use App\Entity\Commande;
use App\Form\CommandeType;
use App\Entity\CommandeProduit;
use Symfony\Component\Mime\Email;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandeController extends AbstractController
{

    private $managerRegistry;

    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry;
    }
    
    #[Route('/commande/confirmation', name: 'app_commande_confirmation')]
    public function confirmationCommande(EntityManagerInterface $entityManager,Request $request, SessionInterface $session,  ProduitRepository $produitRepository ): Response
    {
        //verif si user 
        $this->denyAccessUnLessGranted('ROLE_USER');
        //recup session panier
        $panier = $session->get('panier', []);
        // dd($panier);
        $user = $this->getUser();

        $now = new \DateTime();//cree nouvel ojet date
        $commande = new Commande();//cree nouvel instance commande

        $commande->setUser($user);//attribue le user a la commande
        $commande->setDateCommande($now);//attribue date a la commande

        $form = $this->createForm(CommandeType::class, $commande);//cree le form pour l'objet commandde
        $form->handleRequest($request);// initialise le form

        if($form->isSubmitted() && $form->isValid()){
            $entityManager = $this->managerRegistry->getManager();
            //persist et enregistre l'objet commande
            $entityManager->persist($commande);
            $entityManager->flush();

            foreach( $panier as $prod => $qtt) {
                $produit = $produitRepository->find($prod);
                $commandeProduit = new CommandeProduit();

                $commandeProduit->setProduit($produit);
                $commandeProduit->setQtt($qtt);
                $commandeProduit->setCommande($commande);
                 //persist et enregistre 
                $entityManager->persist($commandeProduit);
                $entityManager->flush();
            }

            //vide le panier
            $session->set('panier', []);

            return $this->redirectToRoute('app_commande_recap', ['id' => $commande->getId()]);
        }

           // Si le panier est vide, redirige l'utilisateur vers la page d'accueil.
           if ($panier === []) {
            return $this->redirectToRoute('app_home');
        }

        return $this->render('commande/index.html.twig',[
            'commandeForm' =>$form->createView(),
            'reference' => $commande->getId()
        ]);
    }

    #[Route('/commande/recap/{id}', name: 'app_commande_recap')]
    public function recap($id, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        $commande = $entityManager->getRepository(Commande::class)->find($id);

        if(!$commande) {
            throw $this->createNotFoundException('commande introuvable');
        }

        $total = 0;

        foreach($commande->getCommandeProduits() as $panier){
            $total += $panier->getProduit()->getPrix() * $panier->getQtt();
        }

        // $this->sendOrderConfirmationEmail($mailer, $commande);

        return $this->render('commande/valid.html.twig', [
            'commande' => $commande, // données à passer au template
            'total' => $total
        ]);
    }

    // private function sendOrderConfirmationEmail(MailerInterface $mailer, Commande $commande): void
    // {
    //     $total = 0;
    //     foreach ($commande->getcommandeProduits() as $panier) {
    //         $total += $panier->getProduit()->getPrix() * $panier->getQtt();
    //     } 

    //     $email = (new Email())
    //         ->from('adminBarberShop@mail.com') // Remplacez par votre adresse email
    //         ->to($commande->getUser()->getEmail())
    //         ->addTo('adminE-commerce@mail.com')
    //         ->subject('Confirmation de votre commande')
    //         ->html($this->renderView(
    //             'commande/emailConfirmation.html.twig',[
    //                 'commande' => $commande,
    //                 'total' => $total
    //             ]
    //         ));


    //     $mailer->send($email);
    // }

    // #[Route('/commande/pdf/{id}', name: 'app_commande_pdf')]
    // public function generatePdf(int $id, EntityManagerInterface $entityManager): Response
    // {
    //     // Récupérer la commande
    //     $commande = $entityManager->getRepository(Commande::class)->find($id);
    
    //     // Gérer l'erreur si la commande n'existe pas
    //     if (!$commande) {
    //         throw $this->createNotFoundException('La commande n\'a pas été trouvée.');
    //     }
    
    //     // Calculer le total
    //     $total = 0;
    //     foreach ($commande->getCommandeProduits() as $produitCommande) {
    //         $total += $produitCommande->getProduit()->getPrix() * $produitCommande->getQtt();
    //     }
    
    //     // Générer le HTML du PDF
    //     $html = $this->renderView('commande/fiche_pdf.html.twig', [
    //         'commande' => $commande,
    //         'total' => $total,
    //     ]);
    
    //     // Configurer Dompdf
    //     $dompdf = new Dompdf();
    //     $dompdf->setPaper('A4');
    //     $dompdf->loadHtml($html);
    
    //     // Rendu et envoi du PDF
    //     $pdfOutput = $dompdf->output();
    //     $response = new Response($pdfOutput);
    //     $response->headers->set('Content-Type', 'application/pdf');
    //     $response->headers->set('Content-Disposition', 'attachment; filename="commande_' . $id . '.pdf"');
    
    //     return $response;
    // }
}

templates/commande/emailConfirmation.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Récapitulatif de la commande</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
        }
        h1, h2 {
            color: #333;
        }
        .fiche {
            width: 100%;
            border-collapse: collapse;
        }
        .fiche th, .fiche td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .fiche th {
            background-color: #f2f2f2;
        }
        .total {
            font-weight: bold;
            text-align: right;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Commande #{{ commande.id }}</h1>
        <p>Bon de commande: {{ commande.dateCommande|date('d/m/Y') }}</p>

        <h2>Informations du Client</h2>
        <p>Nom: {{ commande.nom }}</p>
        <p>Prénom: {{ commande.prenom }}</p>
        <p>Adresse: {{ commande.adresse }}, {{ commande.cp }} {{ commande.ville }}</p>

        <h2>Détails de la Commande</h2>
        <table class="fiche">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Quantité</th>
                    <th>Prix</th>
                </tr>
            </thead>
            <tbody>
                {% if commande.commandeProduits is not empty %}
                {% for commandeProduit in commande.commandeProduits %}
                    <tr>
                        <td>{{ commandeProduit.produit.name }}</td>
                        <td>{{ commandeProduit.qtt }}</td>
                        <td>{{ commandeProduit.produit.prix * commandeProduit.qtt }} €</td>
                    </tr>  
                {% endfor %} 
                {% else %}
                    <tr>
                        <td colspan="3">Aucun produit associé à cette commande.</td>
                    </tr>
                {% endif %} 
            </tbody>
        </table>
        <div class="total">
            <p>Montant total : {{ total }} €</p>
        </div>
    </div>
</body>
</html>

templates/commande/fiche_pdf.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Récapitulatif de la commande</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
        }
        h1, h2 {
            color: #333;
        }
        .fiche {
            width: 100%;
            border-collapse: collapse;
        }
        .fiche th, .fiche td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .fiche th {
            background-color: #f2f2f2;
        }
        .total {
            font-weight: bold;
            text-align: right;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Commande #{{ commande.id }}</h1>
        <p>Bon de commande: {{ commande.dateCommande|date('d/m/Y') }}</p>

        <h2>Informations du Client</h2>
        <p>Nom: {{ commande.nom }}</p>
        <p>Prénom: {{ commande.prenom }}</p>
        <p>Adresse: {{ commande.adresse }}, {{ commande.cp }} {{ commande.ville }}</p>

        <h2>Détails de la Commande</h2>
        <table class="fiche">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Quantité</th>
                    <th>Prix</th>
                </tr>
            </thead>
            <tbody>
                {% if commande.commandeProduits is not empty %}
                {% for commandeProduit in commande.commandeProduits %}
                    <tr>
                        <td>{{ commandeProduit.produit.name }}</td>
                        <td>{{ commandeProduit.qtt }}</td>
                        <td>{{ commandeProduit.produit.prix * commandeProduit.qtt }} €</td>
                    </tr>  
                {% endfor %} 
                {% else %}
                    <tr>
                        <td colspan="3">Aucun produit associé à cette commande.</td>
                    </tr>
                {% endif %} 
            </tbody>
        </table>
        <div class="total">
            <p>Montant total : {{ total }} €</p>
        </div>
    </div>
</body>
</html>

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
<div class="validCommandePage">
    <div class="recap">
        <div class="mb-8">
            <h2 class="text-black font-semibold text-3xl text-center mt-10 mb-4">Info Commande</h2>
            {{ form_errors(commandeForm) }}
        </div>
        <div class="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-4 mt-10">
            {{ form_start(commandeForm, {'attr': {'class': 'space-y-4'}}) }}
                {{ form_row(commandeForm.nom, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                {{ form_row(commandeForm.prenom, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                {{ form_row(commandeForm.adresse, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                {{ form_row(commandeForm.cp, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                {{ form_row(commandeForm.ville, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}
                {{ form_row(commandeForm.numTel, {'attr': {'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}}) }}

                <button type="submit" class="inline-block bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700 transition duration-150 ease-in-out">Valider</button>
            {{ form_end(commandeForm) }}
        </div>
    </div>
</div>
{% endblock %}

templates/commande/valid.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recapitulatif de la commande {% endblock %}

{% block body %}
<div class="validCommandePage">
    <div class="recap">
        <div class="mb-8">
            <h2 class="text-black font-semibold text-3xl text-center mt-10 mb-4">Votre récapitulatif de commande</h2>
            <h3 class="text-black font-semibold text-2xl text-center mb-2">Commande #{{ commande.id }}</h3>
            <p class="dateCom text-gray-600 font-semibold text-center">Date de commande: {{ commande.dateCommande|date('d/m/Y') }}</p>
        </div>
        <div>
            <h4 class="text-black font-semibold text-xl text-start mb-2">Vos informations</h4>
            <p class="text-gray-600 font-semibold text-start mb-2">Nom: {{ commande.nom }}</p>
            <p class="text-gray-600 font-semibold text-start mb-2">Prénom: {{ commande.prenom }}</p>
            <p class="text-gray-600 font-semibold text-start mb-2">Adresse: {{ commande.adresse }}, {{ commande.cp }} {{ commande.ville }}</p>
        </div>
        
        <div class="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-4 mt-10">
            <h4 class="text-black font-semibold text-xl text-center mb-4">Détails de la Commande</h4>
            <table class="min-w-full divide-y divide-gray-200 table-auto border-collapse border border-black">
                <thead class="bg-gray-200">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Produit</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Quantité</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border-b border-black">Prix</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% if commande.commandeProduits is not empty %}
                    {% for commandeProduit in commande.commandeProduits %}
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap">{{ commandeProduit.produit.name }}</td>
                        <td class="px-6 py-4 whitespace-nowrap">{{ commandeProduit.qtt }}</td>
                        <td class="px-6 py-4 whitespace-nowrap">{{ commandeProduit.produit.prix * commandeProduit.qtt }} €</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="3" class="px-6 py-4 whitespace-nowrap text-center">Aucun produit associé à cette commande.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
            <div class="mt-4">
                <p class="text-lg">Montant total : <span class="font-semibold">{{ total }} €</span></p>
            </div>
            
            <form method="POST" action="{{path('payment_stripe', {reference: reference})}}">
                <button class="inline-block mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700 transition duration-150 ease-in-out">Payer par stripe</button>
            </form>
        </div>
    </div>


</div>

{% endblock %}